# Esercitazione 4 Marzo 2025

In [2]:
import time
import numpy as np

## Esercizio 1
- Costruire due array numpy-array 2d di dimensione 5000x5000 i cui valori sono campionati da una distribuzione gaussiana con media 0 e varianza 1.
- Effetuare la somma tra le due matrici con due metodi:

        -  utilizzando le operazioni vettoriali 
        -  considerando due cicli espliciti annidati, su righe e colonne
- Confrontare le prestazioni in termini di tempo di esecuzione.
        


In [22]:
start = time.perf_counter()
arr1 = np.random.randn(5000,5000)
arr2 = np.random.randn(5000,5000)
sum1 = arr1 + arr2
end = time.perf_counter()
print(end-start)

start = time.perf_counter()
sum2 = np.zeros_like(arr1)
for i in range(5000):
    for j in range(5000):
        sum2[i,j] = arr1[i,j] + arr2[i,j]
end = time.perf_counter()
print(end-start)


0.6876328999987891
13.598154799999975


## Esercizio 2
-      Costruire il numpy array  s  formato da 40 valori equidistanti in  [0,20],
-      considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne e dire se il reshape crea una vista o una copia

In [17]:
s = np.linspace(0, 20, 40)
print(s.shape)
print(s.ndim)
s = s.reshape(4,10)
print(s.shape)
print(s.ndim)
#creo una vista, cioè...?

(40,)
1
(4, 10)
2


## Esercizio 3
-     Costruire il numpy array t formato da 100 valori equidistanti in  [0,4]
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [21]:
t = np.linspace(0, 4, 100)
print(t.shape)
t = t.reshape(25, 4)
print(t.shape)

(100,)
(25, 4)


## Esercizio 4
Costruire il numpy array 1d C  di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente).  

In [37]:
c = np.array([x for x in range(15,42,2)])
print(c)
c.resize(7,2)
print(c)

[15 17 19 21 23 25 27 29 31 33 35 37 39 41]
[[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39 41]]


 ## Esercizio 5
 Creare un array NumPy di 10 numeri interi casuali tra 1 e 100.
 

In [25]:
rand = np.random.randint(1, 101, 10)
print(rand)

[ 12   4  70 100  51  96  84  71  62  18]


 ## Esercizio 6
 Eseguire uno shuffle degli elementi di un numpy-array di 30 numeri interi casuali tra 100 e 200.


In [27]:
np.random.shuffle(rand)
print(rand)

[ 18  71  12  70 100  84  62  96  51   4]


  ## Esercizio 7
 Creare una permutazione casuale degli elementi di un numpy-array di 20 valori campionati da una distribuzione  gaussiana con media zero e varianza 1, senza modificarlo.

In [29]:
ran_gauss = np.random.randn(20)
print(ran_gauss)
perm = np.random.permutation(ran_gauss)
print(perm)

[-1.0733037   0.83233993  0.6955546  -0.59463378  1.01920059 -1.03843657
 -0.51265004 -1.09591603  1.02958086  1.41293223 -1.77109323 -1.62442561
 -0.61222097 -0.75853706  0.2401404  -0.62211221 -0.93110116 -0.68328358
 -0.45626488 -0.50924096]
[-0.62211221 -0.68328358 -0.93110116 -1.0733037   0.2401404   1.01920059
 -0.51265004  1.02958086 -0.75853706  1.41293223 -1.62442561 -0.61222097
 -1.77109323 -0.45626488  0.6955546  -1.03843657 -0.59463378 -1.09591603
 -0.50924096  0.83233993]


 ## Esercizio 8
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [31]:
a = np.array([[10,11,12],[13,14,15],[16,17,18]])
view = a.ravel()
print(view)

[10 11 12 13 14 15 16 17 18]


## Esercizio 9
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [32]:
a = np.array([[10,11,12],[13,14,15],[16,17,18]])
copy = a.flatten()
print(copy)

[10 11 12 13 14 15 16 17 18]


 ## Esercizio 10
-     creare i due  numpy array 1d
        f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
        f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
-     "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [39]:
f1 = np.array([ 0,  1,  2,  3,  4,  5,  6, 7,  8,  9, 10, 11, 12, 13, 14, 15])
f2 = np.array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])
print(f1.reshape(4,4) @ f2.reshape(4,4))

[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]


## Esercizio 11
Costruire:
 -     Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 "Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B


In [45]:
a = np.random.randn(2,10)
b = np.array([x for x in range(0,20)])
print(a.ravel() + b)

[-1.07996347  0.16414461  1.44363398  3.72597169  4.45654132  3.64133703
  8.39813782  6.57696113  8.62995152  7.64902647 10.11788502 11.59255301
 13.41076049 13.63594091 15.61091099 14.75723398 15.14870685 16.84356871
 15.84297365 18.25384211]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[-1.07996347 -0.83585539 -0.55636602  0.72597169  0.45654132 -1.35866297
   2.39813782 -0.42303887  0.62995152 -1.35097353]
 [ 0.11788502  0.59255301  1.41076049  0.63594091  1.61091099 -0.24276602
  -0.85129315 -0.15643129 -2.15702635 -0.74615789]]


(2, 10)

## Esercizio 12
-     Costruire f, un numpy array 1D , di shape (10,) costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [51]:
f = np.linspace(0, 1, 10)
print(f)
f.resize(10,1)
print(f)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]


(10, 1)

## Esercizio 13
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe

In [54]:
a= np.array([14,13,12,11])
b= np.array([[4,3,2,1],[9,10,11,12]])
cat = np.concatenate((a.reshape(1,4),b), axis = 0)
print(cat)

[[14 13 12 11]
 [ 4  3  2  1]
 [ 9 10 11 12]]


## Esercizio 14
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

-
- Costruire il numpy array che si ottiene concatenando a e b per colonne

## Esercizio 15
Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale principale, sulla codiagonale inferiore e sulla codiagonale superiore:

elementi diagonali $A_{i,i}=10 \quad$, i=1,20

elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 

elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

## Esercizio 16
Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

## Esercizio 17
Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?

## Esercizio 18
Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

## Esercizio 19

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A/B   dove  $\quad f_{ij}=a_{ij}/b_{ij} \quad i=0,..,n, \quad j=0,...,n$

## Esercizio 20
Dato array NumPy che rappresenta le vendite giornaliere di un negozio per un mese,
vendite = np.random.randint(50, 200, 30) 

        Trova tutti i giorni in cui le vendite sono state superiori a 150.

        Calcola la media delle vendite solo per i giorni in cui sono state superiori a 150.

        Imposta le vendite a 0 per tutti i giorni in cui sono state inferiori a 100.


## Esercizio 21
Costruisci A, un numpy array 2d di shape (3,3) e b,  un numpy array 2d di shape (3,1)
e somma b ad ogni colonna di A b


# Esercizio 22
dato il numpy array 2d G=np.linspace(0,10,20).reshape(-1,4), scambia in G la seconda riga con la quarta riga

## Esercizio 23
Visualizzare il grafico della funzione $f(x)=sin^2(x)/x$ in 200 punti equidistanti nell'intervallo $[0.1,2\pi]$

## Esercizio 24

Data il numpy arra2d ottenuto facendo un reshape a (4,4) di un numpy array 1d di 16 valori equidistanti nell'intervallo [0,4]
ed un numpy array 1d di 4 valori  interi casuali nell'intervallo [10,60], costruire il prodotto scalare A per b,
usando A@b, e vettorizzando solo il ciclo interno.


## Esercizio 25
Dato g un numpy array 2d, estendilo di una riga in alto ed di una riga in basso, di una colonna a sinistra ed di una colonna a destra, usa la funzione g_est= np.pad(g,(1,1),mode='reflect'). Visualizza 'g_est' e commenta cosa vedi.

## Esercizio 26
Scrivi un programma Python che esegua l'elaborazione di un'immagine utilizzando un filtro di media. 

Utilizza il padding per gestire i pixel del bordo durante l'applicazione del filtro.

Il programma deve seguire questi passaggi:

- Carica l'immagine: Carica l'immagine 'cameraman.png' utilizzando la libreria Matplotlib.**image=plt.imread('cameraman.png')**
- Visualizza l'immagine originale **plt.imshow(image,cmap='gray')**
- definisce la dimensione del filtro, dim_filtro
- Applica il padding: Applica un padding costante di dim_filtro//2 pixel a tutti i bordi dell'immagine (utilizzando il metodo di numpy **image_bordered=np.pad(image,(dim_filtro//2,dim_filtro//2),, mode='reflect')**
- Crea il filtro di media: Crea un filtro di media di dimensioni *dim_filtroxdim_filtro*, dove tutti gli elementi sono pari a 1/(dim_filtroxdim_filtro)
- Applica il filtro: Scorri ogni pixel dell'immagine con padding (escludendo i bordi aggiunti) e applica il filtro di media.

   *Per ogni pixel, calcola la somma dei prodotti tra i pixel della sottomatrice dim_filtroxdim_filtro centrata sul pixel corrente e il filtro.*
   
- Crea l'immagine filtrata: Crea un nuovo array NumPy che rappresenta l'immagine filtrata, dove ogni pixel contiene il risultato dell'applicazione del filtro.
- Visualizza l'immagine filtrata: Visualizza l'immagine filtrata utilizzando Matplotlib con la mappa di colori 'gray'.
- Aggiungi una colorbar per visualizzare la scala dei valori dell'immagine filtrata.
- Mostra l'immagine filtrata con Matplotlib.


Requisiti:

-  Utilizzare la libreria Matplotlib per caricare e visualizzare l'immagine.
-  Utilizzare la libreria NumPy per la manipolazione degli array e per il padding.